feat: Add Try it buttons
redhat-developer/app-services-ui-components pull request #229
Opened 2022-03-22 19:15 UTC by srambach

This adds Try it buttons to the Data Science and Overview page as specified in https://issues.redhat.com/browse/RHODS-3174 and https://issues.redhat.com/browse/RHODS-3175.
Also changes the ‘Beta’ button to ‘Field trial’ on Red Hat OpenShift Data Science tile on the overview page.

2022-03-22 19:36 UTC, dlabaj requested changes
Changes look good looks like you have to update the snapshots and make sure you run linting.

2022-03-22 19:40 UTC, riccardo-forina commented on src/AppServices/DataSciencePage/DataSciencePage.tsx
> +            {t("datascienceoverview:heroTryItButton")}{" "}
```suggestion
            {t("datascienceoverview:heroTryItButton")}
```

Is the space needed?

2022-03-22 20:14 UTC, dlabaj approved these changes
LGTM

2022-03-22 20:47 UTC, riccardo-forina commented on src/AppServices/DataSciencePage/DataSciencePage.tsx
> +              ouiaId="button-rhoads-tryit"
We are trying to have tests that explicitly check for changes of OUIA ids whenever we add one. Would you like trying adding one for this? It should be something along the lines of [this test](https://github.com/redhat-developer/app-services-ui-components/blob/dbb11acf6e58ae5a5e3d70b708db43a5e37d4686/src/Kafka/CreateKafkaInstance/CreateKafkaInstance.test.tsx#L9)

2022-03-23 20:17 UTC, riccardo-forina approved these changes
Fantastic, thank you for your help!

2022-03-23 20:38 UTC, merged